# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-16 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='col1',
            field=models.CharField(default=100, max_length=10),
        ),
    ]
